#--------------------------
#
# Github Action
# Lab 1-4
#
#--------------------------

name: MY-GitHubActions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  my_testing:
  
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello Message
      run: echo "Hello World from Testing job"
          
  my_deploy:
  
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello Message
      run: echo "Hello World from Deploy job"
  
  
  
  
